import { levelDataSchema } from "@/schema";
import type { LevelData } from "@/types";

const rawFirstLevel: unknown = {
  id: "sunset-meadow",
  name: "Sunset Meadow",
  summary:
    "A compact test course for movement, coins, enemies, and moving lifts.",
  width: 2_240,
  height: 540,
  spawn: { x: 72, y: 452 },
  platforms: [
    { id: "ground-left", x: 0, y: 500, width: 720, height: 40, tone: "ground" },
    {
      id: "ground-mid",
      x: 820,
      y: 500,
      width: 580,
      height: 40,
      tone: "ground",
    },
    {
      id: "ground-right",
      x: 1_520,
      y: 500,
      width: 720,
      height: 40,
      tone: "ground",
    },
    { id: "step-one", x: 300, y: 420, width: 150, height: 28, tone: "mario" },
    { id: "step-two", x: 540, y: 348, width: 150, height: 28, tone: "grass" },
    {
      id: "lift-one",
      x: 718,
      y: 458,
      width: 88,
      height: 22,
      tone: "grass",
      motion: {
        axis: "x",
        origin: 690,
        distance: 120,
        speed: 72,
        direction: 1,
      },
    },
    {
      id: "bonus-one",
      x: 725,
      y: 318,
      width: 58,
      height: 28,
      tone: "breakable",
    },
    { id: "tower-low", x: 930, y: 424, width: 145, height: 28, tone: "mario" },
    {
      id: "tower-high",
      x: 1_130,
      y: 344,
      width: 165,
      height: 28,
      tone: "grass",
    },
    {
      id: "bonus-two",
      x: 1_325,
      y: 320,
      width: 58,
      height: 28,
      tone: "breakable",
    },
    {
      id: "bridge-one",
      x: 1_390,
      y: 420,
      width: 150,
      height: 28,
      tone: "mario",
    },
    {
      id: "lift-two",
      x: 1_420,
      y: 462,
      width: 92,
      height: 22,
      tone: "grass",
      motion: {
        axis: "x",
        origin: 1_390,
        distance: 130,
        speed: 86,
        direction: -1,
      },
    },
    {
      id: "bridge-two",
      x: 1_650,
      y: 355,
      width: 175,
      height: 28,
      tone: "grass",
    },
    {
      id: "bonus-three",
      x: 1_842,
      y: 318,
      width: 58,
      height: 28,
      tone: "breakable",
    },
    {
      id: "final-step",
      x: 1_910,
      y: 430,
      width: 160,
      height: 28,
      tone: "mario",
    },
  ],
  coins: [
    { id: "coin-one", x: 345, y: 372, width: 22, height: 22 },
    { id: "coin-two", x: 590, y: 300, width: 22, height: 22 },
    { id: "coin-three", x: 980, y: 376, width: 22, height: 22 },
    { id: "coin-four", x: 1_190, y: 296, width: 22, height: 22 },
    { id: "coin-five", x: 1_442, y: 372, width: 22, height: 22 },
    { id: "coin-six", x: 1_710, y: 307, width: 22, height: 22 },
    { id: "coin-seven", x: 1_962, y: 382, width: 22, height: 22 },
  ],
  enemies: [
    {
      id: "enemy-one",
      type: "walker",
      x: 900,
      y: 468,
      width: 34,
      height: 32,
      originX: 900,
      patrolDistance: 260,
      speed: 88,
      direction: 1,
    },
    {
      id: "enemy-two",
      type: "hopper",
      x: 1_610,
      y: 468,
      width: 34,
      height: 32,
      originX: 1_610,
      originY: 468,
      patrolDistance: 280,
      speed: 92,
      direction: -1,
      hopPhaseMs: 0,
      hopHeight: 34,
    },
    {
      id: "enemy-three",
      type: "flyer",
      x: 1_265,
      y: 244,
      width: 36,
      height: 28,
      originX: 1_250,
      originY: 244,
      patrolDistance: 250,
      speed: 82,
      direction: 1,
      wavePhaseMs: 0,
      waveHeight: 30,
    },
  ],
};

export const firstLevel: LevelData = levelDataSchema.parse(rawFirstLevel);
